const CAPACITOR = Symbol('ENVIRONMENT/CAPACITOR');
const ELECTRON = Symbol('ENVIRONMENT/ELECTRON');
const WEB = Symbol('ENVIRONMENT/WEB');
const UNKNOWN = Symbol('ENVIRONMENT/UNKNOWN');

export default {
  CAPACITOR,
  ELECTRON,
  WEB,
  UNKNOWN,
};
