directories:
  output: ./pkg/
appId: org.codaco.networkCanvasInterviewer7
extraMetadata:
  name: network-canvas-interviewer
files:
  - filter:
      - ./dist/**/*
      - ./dist-interviewer/**/*
mac:
  category: public.app-category.education
  target:
    target: dmg
    arch:
      - x64
      - arm64
linux:
  target: appimage
electronVersion: 22.1.0
